development:
  adapter: postgresql
  encoding: utf8
  database: bibapp_development
  username: dylandy
  password: '0000'
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: bibapp_test
  username: dylandy
  password: '0000'
  host: localhost
