development:
  adapter: postgresql
  encoding: utf8
  database: bibapp_development
  username: 
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: bibapp_test
  username: 
  password: 
  host: localhost
