#calculate_ranking:
#  cron: "0 1 * * *"
#  class: CalculateRankings
#  queue: cron
#  description: "Aggiorna i ranking degli utenti"

#update_sitemap:
#  cron: "0 1 * * *"
#  class: UpdateSitemap
#  queue: cron
#  description: "Aggiorna la sitemap del sito"

delete_old_notifications:
  cron: "0 1 * * *"
  class: DeleteOldNotifications
  queue: cron
  description: "Cancella le vecchie notifiche già lette"


count_created_proposals:
  cron: "0 1 * * *"
  class: CountCreatedProposals
  queue: cron
  description: "Conta le proposte create durante il giorno"